### ISSUE TITLE
GoodRead Fix

### ISSUE THREAD

**Issue by Ofsen** [AmunRa1322/Notion-Scripts#1]
Edit:
Hi ! so, after some changes i found out that there is an issue where you can't add covers to more that a certain amount because the goodreads server responds with a 504 Time-out response after a certain time. I changed the code so that it fetchs the covers by chunks of 10 and here are the changes:
```
import notion.client
from bs4 import BeautifulSoup
from urllib.request import urlopen

book_table = []
goodreads_url = "https://www.goodreads.com/book/show/"
client = notion.client.NotionClient(token_v2="---TOKEN---")
cv = client.get_collection_view("---NOTION-DATABASE---")

print('Getting data from Notion...')

for row in cv.collection.get_rows():
    case = {'id': row.id, 'Book_Id': row.Book_Id, 'Image': row.Image}
    book_table.append(case)

print('Splitting the data into chunks of 10 elements...\n')

def split(list_a, chunk_size):
    for i in range(0, len(list_a), chunk_size):
        yield list_a[i:i + chunk_size]

book_table = list(split(book_table, 10))

print(str(len(book_table)) + ' chunks created.')

for idy, valA in enumerate(book_table):
    print('----')
    print('chunk ' + str(idy) + ' in progress')
    for idx, val in enumerate(valA):
        if len(val['Image']) == 0:
            url = goodreads_url + str(val['Book_Id'])
            url_open = urlopen(url)
            soup = BeautifulSoup(url_open, 'html.parser')
            tag = soup.find("img", {"id": "coverImage"})
            try:
                cv.collection.get_rows(search=f"{val['Book_Id']}")[0].Image = tag['src']
                print(str(idx + 1) + ' / 10 - ' + 'Updating: ', cv.collection.get_rows(search=f"{val['Book_Id']}")[0].Image)
            except:
                print("Book:", url, "found with no cover, try changing edition.")
        else:
            print(str(idx + 1) + ' / 10 - The image field is not empty, skipping this...')
    print('chunk ' + str(idy) + ' finished')

```

Old post:

Hello! 

I tried using your code but it seems that the URL of the books changed for some reason. You can't access the book page with just the ```Book_Id``` anymore, it seems like they added a handle to the ```Book_Id```. 

example:
![image](https://user-images.githubusercontent.com/24249806/131496603-cec768eb-5412-4be0-85b8-331e288af3c9.png)

So with some research i found a way to access the book page using the ```ISBN``` with the help of their research page :
![image](https://user-images.githubusercontent.com/24249806/131496773-6b252e7a-dae1-4396-952a-ad87a66c14ff.png)

And here are the changes:
form this : ```goodreads_url = "https://www.goodreads.com/book/show/"```
to this : ```goodreads_url = "https://www.goodreads.com/search?q="```

form this : ```case = {'id': row.id, 'Book_Id': row.Book_Id, 'Image': row.Image}```
to this : ```case = {'id': row.id, 'ISBN': row.ISBN, 'Image': row.Image}```

and finally:
form this : ```url = goodreads_url + str(book_table[idx]['Book_Id'])```
to this : ```url = goodreads_url + book_table[idx]['ISBN']```

let me know if you want me to make a pull request, have a nice day !

**Comment by Ofsen** [comment]
Nevermind it's working now

**Comment by AmunRa1322** [comment]
Hey, Ofsen, I just tried it again your way and you are right. Awesome fix. Yes, please do a pull request.

**Comment by Ofsen** [comment]
Hell yeah ! thank you !! i'll do that when i can
