### ISSUE TITLE
GoodReads update

### ISSUE THREAD

**Issue by codiak** [AmunRa1322/Notion-Scripts#3]
Got excited when I found your script, but ran in to some new issues with "notion.py". It looks like Notion keeps updating things on their side, pushing towards using an official API, so I created a version of your GoodReads script using "notion_client" instead, and relying on an Integration secret:
https://github.com/codiak/notion-scripts/blob/master/goodreads.py

Feel free to copy my code, or point people to this one!

**Comment by AmunRa1322** [comment]
Much appreciated. Glad to see them have an official API. I will point ppl to yours and start using that myself.
